### ISSUE TITLE
master -> libsigmf-v1.0 as default branch

### ISSUE THREAD

**Issue by gmabey** [deepsig/libsigmf#14]
I'm no `git` guru, but it seems a bit confusing to me that `libsigmf-v1.0` isn't the default branch when one lands at https://github.com/deepsig/libsigmf

**Comment by jacobagilbert** [comment]
Hi @gmabey this is not a 'released' branch yet. `main` will be updated soon!

**Comment by gmabey** [comment]
Ok, thank you @jacobagilbert -- I'm starting a new project that needs to write .sigmf files.  Do you recommend I use the `master` branch or `libsigmf-v1.0`?

**Comment by jacobagilbert** [comment]
The v1.0 branch will be 'officially' released soon but it will not have any major changes from what exists today. If you want to be compatible with that or need any of the features described in the readme for 1.0 you should use the v1.0 branch.

**Comment by jacobagilbert** [comment]
`main` is now the default branch, updated to libsigmf-v1.x and `master` is locked.
