### ISSUE TITLE
Lack of read examples

### ISSUE THREAD

**Issue by garengllc** [deepsig/libsigmf#5]
This isn't an issue, but a request.  

It would be nice to see some read examples.  I am writing sigmf files fine via libsigmf, but am having some issues iterating through captures on reads.  A quick example would be helpful.

**Comment by n-west** [comment]
See https://github.com/deepsig/libsigmf/blob/master/examples/example_reading_sigmf_file.cpp

Compile that and run it with an argument that is the path to the example file. It will read in the file to a SigMF record, convert it back to a json object, and print that.
